# Generated by Django 4.2.16 on 2024-11-24 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='tipe',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Deluxe', 'Deluxe'), ('Biasa', 'Biasa')], default='Biasa', max_length=10),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(upload_to='film_posters/'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='kapasitas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studio',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Kursi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('tersedia', models.BooleanField(default=True)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kursi', to='movies.studio')),
            ],
        ),
    ]
