# Generated by Django 4.2.16 on 2024-11-24 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_studio_tipe_alter_film_poster_alter_studio_kapasitas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='kapasitas',
        ),
    ]
