# Generated by Django 4.2.16 on 2024-11-24 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_studio_kapasitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kursi',
            name='kode',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='kursi',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.studio'),
        ),
    ]
