# Generated by Django 4.2.16 on 2024-11-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_kursi_kode_alter_kursi_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kursi',
            name='kode',
            field=models.CharField(max_length=10),
        ),
    ]
