# Generated by Django 4.2.16 on 2024-11-24 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rename_kode_kursi_nomor_remove_kursi_studio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kursi',
            old_name='nomor',
            new_name='kode',
        ),
        migrations.RemoveField(
            model_name='kursi',
            name='status',
        ),
        migrations.AddField(
            model_name='kursi',
            name='studio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.studio'),
        ),
        migrations.AddField(
            model_name='kursi',
            name='tersedia',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='kursi',
            name='jadwal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.jadwal'),
        ),
    ]
