# Generated by Django 4.2.16 on 2024-11-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_kursi_jadwal_alter_kursi_studio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemesanan',
            name='jadwal',
        ),
        migrations.DeleteModel(
            name='Kursi',
        ),
        migrations.DeleteModel(
            name='Pemesanan',
        ),
    ]
