# Generated by Django 4.2.16 on 2024-11-24 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kursi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baris', models.CharField(max_length=1)),
                ('nomor', models.PositiveIntegerField()),
                ('tersedia', models.BooleanField(default=True)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.studio')),
            ],
            options={
                'unique_together': {('studio', 'baris', 'nomor')},
            },
        ),
    ]
