# Generated by Django 4.2.16 on 2024-11-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_kursi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_tiket', models.PositiveIntegerField()),
                ('waktu_pemesanan', models.DateTimeField(auto_now_add=True)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.jadwal')),
                ('kursi', models.ManyToManyField(to='movies.kursi')),
            ],
        ),
    ]
